### ISSUE TITLE
Cant' upgrade

### ISSUE THREAD

**Issue by matjazpotocnik** [neuerituale/PageTableNext#3]
![image](https://user-images.githubusercontent.com/7663992/190711770-ed4fb96a-aa20-44e6-8df2-e15a38dec484.png)

PHP 8.1.9 is very high requirement. I'm on PW 3.0.204 and PHP 8.1.9...

**Comment by julianwinkel** [comment]
Oh sorry. Now the versions are hardcoded and it should work.
Required is: ProcessWire>=3.0.179 with PHP>=7.4.0
